### ISSUE TITLE
Feature: Better access to blocks past prune level

### ISSUE THREAD

**Issue by DeftNerd** [btc1/bitcoin#106]
### The Problem
Many people are unable to run a full-node with full storage of the blockchain. Either they're on limited equipment or do not wish to pay for the storage on a cloud service. Bitcoins larger block size and  increasing usage could accelerate storage requirements. 

### The basic solution
It would be great to be able to configure pruning of the primary block storage directory but copy the blocks to a secondary storage location available on the filesystem. 

This would be great for people who have a SSD and a regular hard drive. The SSD could hold the last few hundred blocks and the spinning disk could hold the older ones. 

### A more advanced solution
If the block storage system could use a filesystem abstraction layer, there could be a community  contributed or 3rd party plugin repository. The configuration should also be flexible enough to allow for multiple block storage locations, replicated block storage, read-only block storage, etc. 

This could allow for some advanced configurations by setting config file parameters. The INI file format is a bit limiting, but I'm sure it could be adapted. There is plenty of bikeshedding that can take place with this portion of the concept

```
# blockstorage=start[-end] [ro/wo/rw=default] uri [driver] [options] [failok]
blockstorage=1-100 file:// forceprune
blockstorage=101 file://mnt/storage/bitcoin
blockstorage=101-1000 s3://accesskey:secretkey@bucketname.s3.amazonaws.com
blockstorage=1 wo sftp://user:password@1.2.3.4/bitcoin failok
blockstorage=500 ro sftp://user:password@1.2.3.4/bitcoin
blockstorage=200 ro s3://bucketname.s3.amazonaws.com
blockstorage=1 ro https://blockchain.info blockchaininfo apikey=123456
blockstorage=1 ro https://blockcypher.com blockcypher apikey=234567
```

The filesystem abstraction layer would keep the config in memory. When a new block is discovered from the network, bitcoin goes through the array of configs to see all the locations to be written to and a index file is updated. Then the index file is analyzed to determine if any locations have blocks that are supposed to be moved. The block data is read, written to the new location, and then removed from the old location. If blocks just need to be purged, the read and write actions are skipped. 

In the previous config example, assuming that all of the storage locations are populated, the following would happen when a new block is received:

* Add latest block to file:// (default block storage location)
* Add latest block to sftp://user:password@1.2.3.4/bitcoin (perhaps an archival location shared among other bitcoin peers) If unable to connect, no problem. 
* Read blocks less than 100 blocks from the current height from file://
* Check file://mnt/storage/bitcoin to see if those blocks are already stored. If not, add them
* Check s3://accesskey:secretkey@bucketname.s3.amazonaws.com to see if the blocks are already stored. If not, write them to the location. 
* Check sftp://user:password@1.2.3.4/bitcoin to see if the blocks are already stored. If not, add them. If unable to connect, no problem. 
* If any of the locations to write failed (unless failok was specified), normally the blocks would be kept in the default location.... but forceprune was specified so they're pruned anyway. 

### Conclusion

There is a bit more to consider, but I'm just trying to give a broad overview of the concepts. Such a configuration would allow for very light nodes that still have access to archival blocks when necessary.

Your thoughts?

**Comment by christophebiocca** [comment]
One thing to note is that you could always redownload blocks from your peers if need be.

So I totally get usefulness of the multiple-disks situation: it would certainly be eaier for most operators than setting up `lvmcache`, and more space-efficient to boot.

However, the instant we're talking about using on-the-network storage, we have to answer the question "what's the goal of doing this?". I'm a little bit unclear about that last part:

- Is it because you'd want to access the not-on-disk blocks frequently but don't want to drain peers' bandwidth?
- Is it because the storage solution you use can provide guaranteed/fast bandwidth?
- Something else?

**Comment by DeftNerd** [comment]
I went a bit too far with the examples, but I do see a progression of use cases. 

* Common use case would be the multiple disk solution. 
* Next would be the ability for multiple clients on a local network to keep some blocks but share archival blocks
* Next use case would be specifying services or hosts with archival blocks to reduce outbound connection requests to nodes that might be on the wrong chain. 
* Next use case might be services that store archival blocks and add additional data that could eventually be parsed by Bitcoin. Not sure what those might be offhand. 
* Archival blocks being hosted by a service on a CDN could be much faster to access (especially when first starting up or during the initial sync). If you need an archival block now, you ask your peers. They might not have it so you have to ask another... which can be delayed by peer discovery.
* This might help allow for pruned nodes to continue to function if any P2P disruptions occur as the result of wide-spread DDoS attacks or protocol attacks (like what happened with Bitcoin Unlimited)

It might be adding too much complication at the moment but it's an interesting concept. If we could add a filesystem abstraction layer (that initially just has a filesystem deiver) and pruning could be adjusted to  support moving rather than just deleting blocks, it could be extended later to support other use cases.

**Comment by christophebiocca** [comment]
That helps me understand the use cases better.

> If you need an archival block now, you ask your peers. They might not have it so you have to ask another... which can be delayed by peer discovery.

My understanding is that only peers which store the entire history enable NODE_NETWORK. Is that not the case anymore?

For everything past multiple-on-disk-paths, the by-far simplest strategy I can think of would be to just call out to a user provided script.

This is what Postgres does for [storing its WAL segments](https://www.postgresql.org/docs/9.6/static/continuous-archiving.html) once they're no longer needed by the local node.

You _could_ just provide two hooks:

- `prunecmd` A command to call when a block is about to be pruned. It gets the header_hash as an argument, and the block contents on stdin, and does whatever it wants with them. If it returns anything other than `0`, that's an error and the block isn't pruned. This is very similar to `-blocknotify`.
- `readcmd` A command to call when fetching a block we don't already have. It gets a header_hash as an argument and streams the data on stdout. If it exits with an error code, or returns bad or incomplete data, or any other problem, the node falls back to its standard fetching mechanisms.

Still not sure how much use it would get, but it has the advantage of having a clear security boundary between trusted code that shares memory-space and untrusted code (Anything linked with the main code could potentially read private keys, so you want to be careful). It also allows people to come up with new solutions running in their prefered language without running through a lot of code review and justifying their use cases, etc.

Such a node would still consider itself pruned for network purposes: It can't give you a block it doesn't store locally, because it has no idea how cheap or expensive getting that block back might be.

**Comment by DeftNerd** [comment]
> My understanding is that only peers which store the entire history enable NODE_NETWORK. Is that not the case anymore?

You are correct, I forgot about that. 

> Such a node would still consider itself pruned for network purposes: It can't give you a block it doesn't store locally, because it has no idea how cheap or expensive getting that block back might be.

Also an excellent point. 

> For everything past multiple-on-disk-paths, the by-far simplest strategy I can think of would be to just call out to a user provided script.
> [ideas about hooks]

That's a brilliant solution! It gives enough flexibility for custom solutions that edge cases might have. It also means that a big rewrite of filesystem code wouldn't be necessary.

**Comment by earonesty** [comment]
In general the Bitcoin source needs more hooks.   RPC hooks, protocol hooks, etc.   Indeed, everything that is not part of the base consensus layer and ledger should probably be adaptable.   Alternate storage formats and solutions should definitely be something that you install a plugin for, not something that's baked in.   The apache "module" system has weathered a long service and something like that would work well for Bitcoin.   dlopen/dlclose with a versioned series of extern-C handlers that are called in order.   

I'm certain a storage hook would be welcomed in many Bitcoin projects.
