### ISSUE TITLE
Who wil be the devs of SW2X?

### ISSUE THREAD

**Issue by DesWurstes** [btc1/bitcoin#112]
Jeff, it looks like you're going to maintain this project (welcome!). Other than you, who is going maintain this repo?

**Comment by jgarzik** [comment]
It's an open project - Anybody who hangs out and contributes meaningfully

**Comment by booung** [comment]
1. @jgarzik this is valid question not sure why it was closed so fast? Apologies if I have this wrong but is this the btc1 dev activity https://github.com/btc1/bitcoin/commits/segwit2x compared to core https://github.com/bitcoin/bitcoin/commits/master ? This is concerning as btc1 seems deserted compared to core.

2. Who of the top exchanges (https://coinmarketcap.com/exchanges/volume/24-hour/) have committed to running btc1?

3. I know a majority of miners have committed to this project but for how long? The market (users on the exchanges) will determine the price of the btc1 and core chains and miners may switch to core if users determine it has value. I know the core chain may have slower transactions\difficulty issues (apologies if I have this wrong) but my understanding is this wont affect trading and therefor the price?

**Comment by JaredR26** [comment]
> @jgarzik this is valid question not sure why it was closed so fast?

It's closed because it isn't an actual issue with the codebase and open issues are reserved for problems and priority changes.  Jeff has said in the past discussion can continue on closed issues.

> Apologies if I have this wrong but is this the btc1 dev activity https://github.com/btc1/bitcoin/commits/segwit2x compared to core https://github.com/bitcoin/bitcoin/commits/master ?

If you're on a phone, you might have to go back in time to see more activity, as core's activity has ramped up in the last month in preparation for 0.15.0 and btc1's activity has declined after 0.14.5 RC2 was completed.  Regardless of that, it would not be a good idea for btc1 to attempt to do so many commits like that, as the current intention is to remain compatible with Core as much as possible(Unlike what BU did), bringing most improvements forward; Every change increases the difficulty of that merge, so it would need to be an actual bugfix that is unique to the btc1 codebase and not the core codebase.

Finally, for the next 3 months, btc1 development is definitely going to be slower as compared with Core.  The efforts of all of our volunteers are dedicated to ensuring the smoothest launch possible, and the vast majority of that involves things outside this codebase (User and business communication and assistance for the upgrade, working with interrelated software to upgrade, network robustness, etc).  It is only after that point that btc1 will begin serious development, as many of the things we would like to begin working on are barely even worth discussing prior to a successful and smooth fork.  I don't know when the btc1 and core codebases might diverge completely and stop bringing core improvements forward.

That said, discussions have already started about other projects that are very much needed in Bitcoin, among them UTXO commitments (warp sync as many other coins have already) and improvements to the segwit discount's poor targeting of UTXO bloat.  But none of those are priorities compared with the importance of a smooth and successful upgrade for the ecosystem.

> Who of the top exchanges (https://coinmarketcap.com/exchanges/volume/24-hour/) have committed to running btc1?

A lot of them, and some of them already are running btc1.  Bitpay, Xapo, Purse.io, BitWala, and Circle aren't exchanges directly but they do drive substantial volume across multiple exchanges.  Genesis Trading has a substantial OTC volume.  Coinbase(GDAX), OKCoin, Korbit, Huobi, BitFlyer, BTER, BTCC, and Shapeshift all drive substantial volume.  Some other smaller ones include ViaBTC, Bitso, Luno, SurBTC, BitOasis, Ripio, BitPesa, and Bixin.  All of these are signatories.

Some of the others are essentially guaranteed to follow the most PoW chain in the event of a fork, such as Gemini(SEC filing requirement).  To my knowledge, not a single large or medium sized exchange has said they will *not* follow the most-PoW fork, and no large business except for Blockstream has said they will not.

> The market (users on the exchanges) will determine the price of the btc1 and core chains and miners may switch to core if users determine it has value.

It will take substantial time (days or weeks) for the core chain to actually have a reliable value, much like it took several days for BCH - even with its rapid difficulty decreases - to actually have a meaningful price on exchanges.

The Core chain will be much worse off than BCH was.  The first core-only coins won't be spendable for 120 blocks; At 7% of the hashrate that's nearly 2 weeks before the first minted coins are spendable.  The transaction volume on that chain would go from ~250k+ to ~17.5k per day, times 1.7x whatever percentage of active UTXO's have converted to segwit by then, and it will have to bear the load of not only the existing transaction load but also the transactions from non-core supporters wishing to sell the corecoin before the price crashes.

> I know a majority of miners have committed to this project but for how long?

This isn't clear, but equally unclear is what will happen to the 7% that isn't signaling /NYA/.  11% of Slush's pool, the only non-NYA-signaling pool, supports 2x, and only 48% support Core.  The only non-Slush blocks that aren't tagging support for /NYA/ are unmarked, unreliable, and unknown.  Given the frustration that will exist on the Core chain from the massive reduction in transaction volume, it is quite likely that **only** the 48% voting Core on Slush's pool will stick it out driven by their philosophy.  That's 183 PH/s out of the network's 6140 PH/s, or a little under 3%.  If that's all that remains, the transaction capacity will drop to less than 10,000 tx/day, and that stuck volume would take more than 9 months to reach the first difficulty change, and even _that_ would only be a half difficulty step; Resuming full speed would be basically a year away.

In this state, the legacy chain would only be including the transactions that are in the top 2% of the highest fees on the 2x chain.  The chain will be effectively unusable without a hardfork.  So yes, it absolutely will affect trading and price, if the Core chain can even get a price in the first place.

As Jeff said, you and anyone else are welcome to step up and contribute changes that you think BTC1 needs for review.

**Comment by mpatc** [comment]
> and that stuck volume would take more than 9 months to reach the first difficulty change, and even that would only be a half difficulty step; Resuming full speed would be basically a year away.

[core is already signaling](https://github.com/BitcoinHardfork/bitcoin) for an emergency hard fork, because nobody likes losing power as it seems they're about to, therefore, I don't think anyone can count on their legacy chain 1mb chain stopping naturally. I'm thinking they'll limp along similarly to Eth Classic.

**Comment by Buck-Rogers** [comment]
@mpatc  To avoid a slow difficulty change core would need replay protection and a POW change....and when you see that it is an admission of defeat.
