### ISSUE TITLE
btc1 possibly (likely imo) doesn't have the consensus its needs to pull of the HF without creating a split 

### ISSUE THREAD

**Issue by booung** [btc1/bitcoin#114]
I brought up some of these issues in the replay protection discussion but decided they might be better in a separate issue:

1. Will btc1 abandon the project if it looks like it may cause a split as that goes against the goal of remaining one chain?

2. I just checked https://coinmarketcap.com/exchanges/volume/24-hour/ compared to https://medium.com/@DCGco/bitcoin-scaling-agreement-at-consensus-2017-133521fe9a77 and only 4 of the top 20 exchanges have committed to the NYA and there is also this list http://nob2x.org/. I know most of these businesses haven't said they wont follow btc1 but that's far from committing to it. As its a HF they will need to upgrade/change code and are therefore currently incompatible with btc1 and will cause a split (apologies if I have this wrong)

3. https://cash.coin.dance/blocks/thisweek shows bitcoin.com, BTC.com, Antpool, BitClub, and ViaBTC are all now mining another chain. These companies all signed the NYA but are now mining something else proving that hashpower can change and (used by itself) may not be a good measure for consensus.

4. There also doesn't seem to be many people running btc1 yet https://coin.dance/nodes is this accurate?

No offence to JaredR26 and I'm happy for him to respond but it would great to get a response from you @jgarzik as you are the main dev for this project

**Comment by jheathco** [comment]
@booung github should be reserved for technical issues.  Please take these questions to the slack chat.

**Comment by booung** [comment]
@jgarzik I was told to ask this on slack but no response from you there do I have to post this to the mailing list and twitter or can I please just get a response here? As well as posting the above questions I also asked this:

"A big question I think we need answered is will this project have at least >80% of the major exchanges on board as so far doesn't and this is a big problem. Will the project go ahead if it doesn't? @jgarzik  @evoorhees  any update on this? Yes miners are currently signalling NYA but if you think they wont follow the market (users on exchanges) you are IMO in for a big surprise (hint: bcash)"

I did get a response from who Erik Voorhees said this is going to lead to a split and ShapeShift will likely list both chains take a look at the slack chat if you haven't already.

**Comment by jprupp** [comment]
@booung the goal of this project is to perform the SegWit2x hard fork in a way that avoids, but not necessarily prevents, the continued generation of legacy blocks. Businesses, even signatories to the New York Agreement, are free to do as they prefer with regards to whether they will also accommodate legacy blocks as well as the upgraded chain.

Assuming that miner signalling is honest and that the agreement is upheld until the date of the hard fork, then it is expected that at least 90% of the hashrate will go to mine 2x blocks. Since the non-upgraded chain would be left with such a small fraction of mining power (if any), [all kinds of nasty things](https://medium.com/@xenog/what-happens-after-block-494-784-to-bitcoin-clients-that-do-not-upgrade-2e0ebe72587c) are expected to befall on it which makes it impractical to continue building upon it, which is why I recommend completely abandoning it.

**Comment by evoorhees** [comment]
Exchanges will, and should, list both assets.  That is how the market
decides whether the fork is wanted or not.   If it is true that btc1 has
90% miner support and the support of the largest companies, then the market
will likely not be kind to the classic chain.



Kind regards,
-Erik Voorhees

On August 24, 2017 at 3:24:29 AM, Jean-Pierre Rupp (notifications@github.com)
wrote:

@booung <https://github.com/booung> the goal of this project is to perform
the SegWit2x hard fork in a way that avoids, but not necessarily prevents,
the continued generation of legacy blocks. Businesses, even signatories to
the New York Agreement, are free to do as they prefer with regards to
whether they will also accommodate legacy blocks as well as the upgraded
chain.

Assuming that miner signalling is honest and that the agreement is upheld
until the date of the hard fork, then it is expected that at least 90% of
the hashrate will go to mine 2x blocks. Since the non-upgraded chain would
be left with such a small fraction of mining power (if any), all kinds of
nasty things
<https://medium.com/@xenog/what-happens-after-block-494-784-to-bitcoin-clients-that-do-not-upgrade-2e0ebe72587c>
are expected to befall on it which makes it impractical to continue
building upon it, which is why I recommend completely abandoning it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/btc1/bitcoin/issues/114#issuecomment-324582651>, or mute
the thread

**Comment by booung** [comment]
Thanks @evoorhees appreciate you taking the time to answer and totally agree we should let the market decide.
