### ISSUE TITLE
Convert 2M HF flag date to relative date  

### ISSUE THREAD

**Issue by nitsujlangston** [btc1/bitcoin#14]
SEGWIT2X locked in + 3 months

**Comment by opetruzel** [comment]
What's the reasoning for setting it fewer than 6 months?

**Comment by nitsujlangston** [comment]
The 3 month duration is to give the community as much time as possible to prepare while still meeting the stated charter goal of a 2M HF within 6 months of the agreement, based on a planned signal date in July.

**Comment by hmsln** [comment]
Not sure I understand you right here, but I think it would be better to use every single day of those 6 months for HF preparation. A hard fork needs even more research and testing than a soft fork: since by definition it is non backwards-compatible, you want *almost all* the economy to upgrade, so it's better to give nodes and miners enough time.

`LOCKED_HEIGHT + (2016*14) - ((LOCKED_HEIGHT % 2016) - 1)`

That would be better.

**Comment by AllanDoensen** [comment]
If you have 83% support of the miners running this segwit2x fork, why can you not just HF on the same day as the segwit lockin? You would have majority miner support at that point anyway so the smaller chain would most likely disappear because of insufficient HP (there will always be 1M holdouts whatever you do). 

IMHO If you wait 3 months there may not be miner support anymore and the hardfork may then be more painful and more likely to cause a major chain-split. Please consider doing the HF at lock-in time.

**Comment by opetruzel** [comment]
@AllanDoensen
I feel that it would be completely irresponsible to not give the rest of the ecosystem additional time to prepare for the hardfork -- either to install the SegWit2x client, or adapt their services/apps for compatibility. In fact, I feel that 3 months is not enough time either.

**Comment by AllanDoensen** [comment]
I am not a miner. But I think we need to look at the hypothetical of what miners would do. Lets say there are two types of miners that will not adhere to the agreement and seek their own benefit from it:
- “BigBlockOnlyMiner” : miners that are against segwit and just wants big blocks and has 10%+ hashing power.
- “SegwitOnlyMiner” : miners that are against big blocks and just wants segwit and has 30%+ hashing power.  

The current code is for segwit activation at 80% and a HF in September. SegwitOnlyMiner may support the initial activation, but then not support the HF in September. So if segwit activates quickly, then the SegwitOnlyMiner can pull his support for the HF and the HF then causes a major chain split or does not activate. In response to this BigBlockOnlyMiner holds back his support for segwit until the September HF time. Thus causing the HF and Segwit to happen at the same time. IMHO this is the most likely thing that will happen with the current code: segwit and HF happen at the same time in September.  

If we change the design to have the HF at 3Months after the segwit activation what would happen? Well the BigBlockOnlyMiner may choose to not accept this agreement and raise the issue that HF is not guaranteed to happen under this situation. If segwit did activate, then the SegwitOnlyMiner has 3 months to pull his support for the HF & make a lot of noise about how a HF is a bad idea etc. In this situation I think it would be likely that either the HF would fail or there would be a significant chain split. This would not be good, thus I do not like this design. This has the potential to split bitcoin in two and cause so much confusion/anger/mistrust that any users left run to ETH/Dash.

A third option is the HF is activated on the day that segwit activates. As long as it is known in advance I think that can be managed. ‘Getting the community ready’: well I still do not understand what this means, but they have advance warning and the bulk of the miners on the one chain – which is the main thing. It would have the benefit of having segwit & HF active very quickly (rather then in September). This IMHO would be the best option and the least likely to be undermined by untrustworthy miners.

**Comment by NLNicoo** [comment]
You cannot force a HF to everyone. How can you possibly think that pushing for a HF "immediately" in a completely unsafe way is more likely to get support among everyone? It will only give you a lot more resistance.

Since those miners/companies already agreed with a max time of 6 months, the only logical thing is to actually use all of those 6 months. The most safe timeline to do a HF (within the parameters of this agreement) is much more likely to get "consensus among everyone" and therefor causing a smaller chain-split.

Focus should be: how to do the HF as safe as possible so it gets a lot of support from everyone. And not: how to force a HF.

**Comment by kek-coin** [comment]
@AllanDoensen assuming your stats are accurate, it is safe to ignore BigBlockOnlyMiners because 10% of hashrate cannot hold back an 80% signalling activation.

**Comment by jacob-eliosoff** [comment]
Trying to activate segwit and HF simultaneously would provoke huge opposition, and is too much change for one day anyway.

IMHO more productive than that (not gonna happen), and even more productive than debating 3mo vs 6mo right now, is to help build consensus around & implement the HF details ASAP.  The sooner that's done, the more time the community has to prepare, and the less likely miners are to pull out on grounds of footdragging.

**Comment by AllanDoensen** [comment]
@kek-coin if you only have 83% support and 10% of those 'hold back'. Then yes it can. 

I do not believe with the current code that segwit will activate until HF day. Those BigBlockOnlyMiners will take there time doing the 'upgrade' and will not complete it till some day in September. Just like the SegwitOnlyMiners wanting 'as much time as possible' between the activation and the HF - so they can cause mischief and mayhem as well.      

I have no stats. This is not about stats, this is about how humans will/may react. Greg, you cannot collect stats on something like this beforehand because of the humans making cognitive decisions based on what is in their perceived best interests. I am just attempting to figure out what actors may do based on their motivations.

**Comment by stefment** [comment]
Allan, fyi miners are not in a rush to hardfork despite them making it appear so. A rushed hardfork makes them even less likely to do so as far as i can tell.

**Comment by AllanDoensen** [comment]
@stefment The miners are not a single group. They all act differently. To clarify:
 - About 43% of miners are currently running BU or EC. They consider segwit to be dangerous and think that a rushed segwit activation would make them far less likely to support it.
 - 30%+ of miners are currently signalling for Segwit. They consider HF to be dangerous and think that a rushed HF would make them far less likely to support it.

I am not trying to support one group over the other, I am just trying to predict how each group will react to this agreement. 

Maybe you can explain why you think that the 40% of EC/BU miners will signal for segwit prior to the HF date in September? I cannot think of a reason why they would. Can you?

**Comment by stefment** [comment]
If Ethereum overtakes bitcoin that ought to be a wakeup call. But probably it will be too late and Ether will steal the show for a while regardless of what miners do.

**Comment by AllanDoensen** [comment]
@stefment Yes, a wake-up call to *both* groups. It is why I support an earlier segwit/HF activation day, we need to just get this over and done with, the fees are killing bitcoin. Do you have a rational argument for why I am wrong?

**Comment by stefment** [comment]
It seems like supporting SegWit as its currently rolled out is the most practical way of scaling bitcoin which basically means its going to be the fastest. Right? This proposal will only further delay things. This is because it tries to do a hardfork as well, and last i checked, the segwit part isnt even compatible with how segwit is currently rolled out. So if your concern is that bitcoin must scale asap, i dont understand how you can support this. Please correct me if im wrong.

**Comment by AllanDoensen** [comment]
@stefment Your first statement is a subject of debate among these two groups. The BU/EC group which has about 43%+ of hashing power disagrees with it. For a solution to be found you must negotiate with that group & allow both groups to move forward. The absoluteness of your first statement is why you are wrong. Compromise must be reached else the stalemate continues.

**Comment by AllanDoensen** [comment]
Both the bip148/USAF and UAHF are scheduled to occur on August 1st, There is the possibility of up to 3 separate chains being made on August 1st - which may cause significant damage to bitcoins value.  I would prefer a single chain rather then what is shaping up to be guy forks day on August 1st.

I would think it prudent that segwit2x HF day be moved to before this August 1st date.

**Comment by jgarzik** [comment]
@AllanDoensen The HF is months after SegWit activation.

**Comment by AllanDoensen** [comment]
@jgarzik Bitmain has a UAHF 'contingency' plan that happens on Aug 1st with respect to UASF. It includes a 2M HF on Aug 1st. I reference bitmains blog:

https://blog.bitmain.com/en/uahf-contingency-plan-uasf-bip148/

**Comment by aceat64** [comment]
@AllanDoensen As stated in their blog post, Bitmain will only do their HF if SegWit2x doesn't activate before then and BIP148 does. There's no need for SegWit2x to HF before that date, since reaching 80% signalling on bit 4, before Aug 1, will keep BIP148 from causing a split.

**Comment by jacob-eliosoff** [comment]
@aceat64 (@jgarzik) Just to be clear, 80% bit 4 signaling is not technically enough to avert the BIP148 split.  What's needed is for **orphaning of non-bit-1-signaling blocks** to begin by (morning of) Aug 1.  The old BIP91 logic would result in a ~4-week gap between when 80% bit 4 support was reached and when orphaning began, so it's not just an academic distinction.  See my [mail to bitcoin-dev on this timing](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-June/014560.html).

**Comment by AllanDoensen** [comment]
@aceat64 I really hope you are right, but IMHO the assumption that Segwit2x will activate prior to the segwit2x HF day (in September) is unlikely.

**Comment by benkloester** [comment]
It will really depend on whether Bitmain are willing to run Segwit2X, as it is currently implemented (ie compatible with BIP91), or not. 

Is there any indication that they will/won't? They signed the agreement, but Bitmain's recent blog seemed to suggest they want to get rid of the witness discount before supporting Segwit, so the situation is very ambiguous.

**Comment by aceat64** [comment]
@AllanDoensen The SegWit2x HF can't happen until 80% of miners signal bit 4, see the code in PR #11.
