### ISSUE TITLE
effective blocksize 

### ISSUE THREAD

**Issue by stefment** [btc1/bitcoin#15]
Hello there, if this proposal activates and we asume most transactions will be segwit, what will be the effective blocksize in terms of mb?

**Comment by christophebiocca** [comment]
In case anyone else looks here for an answer:

Short answer: anywhere from 2MB-8MB with highest probability of around 2MB-3.4MB, unless further code changes occur.

Long answer: It's complicated, because:

1. The segwit witness data discount *might* change at HF time. This is still being discussed. If it is decreased this would lower the effective max block size from 8MB (at 1/4 weighting) to 4MB (at 1/2) or even 2MB (at full weight).
2. As you noted, actual size depends in large part on segwit adoption. The HF will at least guarantee 2MB of available space even if segwit adoption stays at 0. 
3. The segwit witness data discount *might* be applied to the signature part of legacy transactions. This is still being discussed. This would push us closer to 3.4MB of actual block size, regardless of segwit adoption.
4. If segwit usage is 100% then the effective max block size depends on the ratio of outputs to inputs, and the use of multisignature inputs/outputs.
    1. The expected mix of these things (based on current usage) would lead to an effective 3.4 MB blocksize at capacity.
    2. If people suddenly find themselves all using multisig, this could increase substantially.
    3. Someone deliberately trying to bloat blocks *could* craft transactions with lots of witness data, to push blocks asymptotically close to 8MB (this is why changing the discount is being discussed).
