### ISSUE TITLE
Change client name or add user agent comment to indicate btc1 codebase.

### ISSUE THREAD

**Issue by chaosgrid** [btc1/bitcoin#25]
I'm curently not seeing a way to identify that a node supports the btc1 (SegWit2x) consensus level changes which is especially important for the later planned hard fork. I think for the beta version, either the client name should be changed to something like "SatoshiBTC1", or there should be a default user agent comment like "btc1".

Note: It is uncertain whether the Bitcoin Core project will merge the consenus-critical changes.

**Comment by christophebiocca** [comment]
My 2 cents on that front:

- Historically, node announcing that they run a hard-fork client have been DDOS'ed (I've experienced it myself).
- Node counts are trivially sibylled, and hence not a reliable indicator of anything at all.
- SegWit2X participants are committing to the hardfork, not conditional on "how many hobbyists run this code". Most of them run their own full nodes (or fleet thereof) and have no need for volunteer-run nodes.

Hence a user-agent change is not needed, and mostly counterproductive, in my view. Those who absolutely want to signal support can always change it themselves.

## Update:

As pointed out below there are already visible changes that allow node identification anyways, so there's no real difference in changing the UAComment field or not.

**Comment by GoneUp** [comment]
You should be able to identificate the clients over the new clientversion of 1.14.1 https://github.com/btc1/bitcoin/commit/7c040e60385320d9313b7d3ca32367c5187857d1

**Comment by hihah** [comment]
Even though I am just a "hobbyists running this code" I would like to signal my preferences.
This is the only reason for not running the other client.

**Comment by dja29** [comment]
Denial of service is a real threat to any node that supports alternate consensus rules. 

Perhaps by default the client name should be unique and refer to btc1, but users can run the client with "-stealth <user-agent>" in order to appear as something different.

**Comment by JaredR26** [comment]
Phrasing it as "stealth" sounds shady like it is doing something wrong...

Just my two cents here... While I do think that changing the default useragent is the "right" thing to do in terms of both collecting statistics and node peering effectiveness, I think history shows clearly that this useragent is going to be a DDOS target.  It would be bad if unknowing users got DDOS'd who weren't aware of the non-default flag that might protect them, and it would also be bad if the DDOS attackers were given target lists prior to the hardfork point.  DDOSes post-fork will likely be much weaker if the fork carries a significant portion of the economy with it, and if it is difficult for the attackers to identify targets.

At least until the fork point, and probably for 3-4 weeks afterwards, the segwit2x client should appear to be a core client to all external parties unless the operator specifies otherwise.

The segwit2x seed nodes are going to be heavily, heavily DDOS'd prior to the fork point.

**Comment by jli225** [comment]
I don't think we shall use something like "SatoshiBTC1".

The only reason we had to use GitHub/btc1 is that GitHub/Bitcoin had been hijacked.

The brand name is always for "Bitcoin". So we shall only use "Satoshi" and "Bitcoin" to avoid confusion.

**Comment by kek-coin** [comment]
Any serious node that cannot withstand a DDoS isn't going to be functional after the hardfork time regardless of UAstring if that truly is such a threat. Isn't this going to be visible in the version number anyway? The major version for this repo was bumped from 0 to 1 in a recent commit.

**Comment by jgarzik** [comment]
Correct, the client major version number was bumped, and that's visible.

Given that, closing this now.

**Status**:  Unresolved, might reopen.

**Comment by jgarzik** [comment]
"Reopened" by virtue of creating PR #78 

The logic of this change is discussed in #56 in comment https://github.com/btc1/bitcoin/pull/56#issuecomment-315362592
