### ISSUE TITLE
Hard fork on Block X

### ISSUE THREAD

**Issue by jgarzik** [btc1/bitcoin#29]
The traditional hard fork sequence is

1. Rules change on the chain at block X
2. Sometime later somebody produces a block larger than 1M, and fork occurs.  Perhaps block X+0, perhaps X+1, perhaps X+100 or X+10000.

Tighten this to require a larger-than-1M block when the rule changes, on block X+0.  Doing so creates a more predictable behavior with the network.

Requested by Bitmain and BU to implement an anti-wipeout feature; myself and other WG members concurred via the wider rationale of creating a more predictable network upgrade.

**Comment by jmprcx** [comment]
I'm reading up on the commit history and I can probably work this issue if someone else isn't already.

An issue may arise about how miners will enforce this in the blocks they are generating. It's going to be hard to determine the mempool size at the time of the hardfork and there's a possibility there might not be enough transactions in the mempool to support a larger than 1mb block. 

Is there a plan to fill up the blocks with dummy transactions or to create additional transactions in the event the mempool isn't large enough at the time of the hard fork?

**Comment by christophebiocca** [comment]
I do believe there are specially-crafted transactions that aim to [reward miners](http://www.blockbounties.info/) for making oversized blocks.

As the initial transaction has a size of exactly 1 MB, it would be allowable under the proposed HF rules, and a great candidate for inclusion by the first miner (giving them a substantial reward for participating).

Update: as @dskloet mentions below, this transaction cannot safely be hardcoded, due to the risk of the funder double spending the original transaction.

**Comment by jgarzik** [comment]
@joshuayabut Yes, correct, ensuring that block will filled must be planned-for well in advance.

**Comment by gavinandresen** [comment]
If there aren't enough transactions in the mempool (e.g. you're on testnet) the CreateNewBlock code could add a bunch of zero-value OP_RETURN outputs to the coinbase transaction to make the block bigger than 1MB.

It'd be nice to remember to remove that code six months after the successful hard fork... (at that point it is just technical debt)

**Comment by jmprcx** [comment]
Regarding https://github.com/joshuayabut/bitcoin/commit/12cc975ec60a0760c8491a6478c5dc7ad6be0e5f: I moved the validation routines to ConnectBlock() since it didn't seem there was a good way to rerun downloaded blocks through validation again.

With this implementation the block height at which the validation happens can be modified with `consensus.nSegWit2xHFActivationIndex = 0;` in chainparams.cpp. Setting it to 0 requires a block size increase at the same block height that `DEPLOYMENT_SEGWIT` is activated.

*Note: The DoS level for a block failing to meet the validation requirements is currently set at 0.*

**Comment by luke-jr** [comment]
I think using [the 1 MB transaction](https://www.reddit.com/r/btc/comments/69318u/save_the_chain_enclosed_1_mb_transaction_with_273/) referenced by @christophebiocca is a much better solution than filling the block with `OP_RETURN`s (which would require the miner to keep some UTXO to use as an input). The 1 MB transaction seems to compress very well, so it can just be included with the code and removed later once the first block is mined.

**Comment by dskloet** [comment]
Hard-coding that transaction is a very bad idea because its creator could invalidate it by spending the inputs before activation.

**Comment by theslagter** [comment]
obviously these measures are only taken because there is concern of a split. why not wait with the hardfork until it has actual consensus and is considered safe? its not like it will be the end of the world to wait. please correct me if im wrong.

**Comment by dskloet** [comment]
Is X the block that activates SegWit or is X still 3 months later?

The referenced commit seems to make the HF simultaneous with the SegWit activation (correct me if I'm wrong) but the issue description doesn't seem to say anything about it.

**Comment by opetruzel** [comment]
@dskloet 
I believe that if this were implemented, it would be set to **SegWit Activation + (90*144 blocks)** to match the HF activation code. The example used a setting of zero to demonstrate function, not an actual intent to activate the HF at the same time as the Segwit activation.

**Comment by jgarzik** [comment]
"The traditional hard fork sequence" - OP refers to the HF activation point as X.

Therefore, as @opetruzel notes, it would be **SegWit Activation + (90*144)**.

**Comment by MickSHunt** [comment]
knowing a baseblock of >1mb wont be backward compatible. should we not use this hardfork as an opportunity to just do away with the 2 merkle segregation and just have a complete single block of upto 4mb where serialised(complete) segwit transactions sit side by side with native transactions.

and just let the prunning of segwit signatures (for the benefit of local(within individual node) UTXO be something that becomes locally voluntary, rather than a cesspit of node network communication issues of different block structures

**Comment by magmahindenburg** [comment]
I think Gavin's proposal is the best solution. The simple and not very good alternative is to allow GBT to send a block template that is less than 1Mb, but if the mining pool software finds a solution and submit it to bitcoind, it will be rejected, causing the miners to start working on another block at the same height.

Simple is better.

**Comment by luke-jr** [comment]
@dskloet How about the NYA participants all co-author a similar multisig output that is used for this purpose?

@theslagter With this kind of hardfork, there is a guaranteed split. Furthermore, a large portion of the community has already rejected it, so there is a certain split from that angle as well. Waiting is unlikely to resolve this.

@MickSHunt The 2 merkle trees is what provides some of Segwit's features for light clients (pruning is entirely unrelated). It might make sense to move the txhash tree out of the generation transaction, but either way, two trees are needed. Note that Segwit already serialises complete segwit transactions side-by-side with legacy transactions - the idea that signatures are separated is a myth.

@magmahindenburg Why waste miner energy mining a block that is known in advance to be rejected? It would be better for GBT to fail completely so miners can turn off and save energy until a sufficiently large block can be produced. (But neither should be necessary.)

**Comment by magmahindenburg** [comment]
> Why waste miner energy mining a block that is known in advance to be rejected? It would be better for GBT to fail completely so miners can turn off and save energy until a sufficiently large block can be produced. (But neither should be necessary.)

You can't simply turn off mining chips. Antminer S7 for example would literary burn up if it lost connection to the mining pool, which would happen if GBT fails. This is why all mining pools mine empty blocks once in a while, because they have to. The chips would break otherwise or wear out very fast.

As I said, Gavin's idea makes most sense, but don't even consider GBT completely failing as it would risk breaking miners.

**Comment by jameshilliard** [comment]
No, you would want GBT to fail so that the stratum server switches to a backup node. GBT is supposed to fail if it can't produce a valid template, stratum servers should know how to handle that since it's common when rebooting nodes.

**Comment by Buck-Rogers** [comment]
We would know the exact date that this will happen. There are enough big block supporters that will make certain there is enough 'dust' in the mempool to make a block larger then 1M. 

I think a better plan would be to orphan any block that does not signal bit 4 at the HF date. Or maybe a month before the hardfork date start orphaning.  So that we know that the chain has majority support prior to the HF - the orphaning would be a soft fork that would force miners to upgrade.

**Comment by luke-jr** [comment]
@Buck-Rogers If the goal is to simply avoid reorg risk, and not necessarily make a >1 MB block at the chain split point, a better solution would be to simply require the "hardfork bit" (the top/sign bit) to be set on new blocks.

**Comment by jameshilliard** [comment]
> I think a better plan would be to orphan any block that does not signal bit 4 at the HF date. Or maybe a month before the hardfork date start orphaning. So that we know that the chain has majority support prior to the HF - the orphaning would be a soft fork that would force miners to upgrade.

This wouldn't work since it would simply force false signalling for any miners that intend to reject the HF.

> a better solution would be to simply require the "hardfork bit" (the top/sign bit) to be set on new blocks

I think this is a better idea since it should work with SPV wallets that only validate headers while a large block probably won't work.

**Comment by NiKiZe** [comment]
@jameshilliard I for one would rather see false signaling in blocks then someone determining by signaling that HF wont happen.

The whole point of the agreement is to have segwit and 2MB, having one without the other won't be acceptable, so it makes no sense in trying to have a flag for which supports the 2MB part and who doesn't since everyone must support it. From a psychological point of view it will be much better for everyone to see that 2MB will happen, that in itself will discourage any false signaling.

If there going to be anyone rejecting a HF then they will have to find some other way then signaling to make sure they are a majority.

**Comment by jameshilliard** [comment]
> I for one would rather see false signaling in blocks then someone determining by signaling that HF wont happen.

This is an incompatible HF so that means it will fork no matter what once locked in.

> The whole point of the agreement is to have segwit and 2MB, having one without the other won't be acceptable, so it makes no sense in trying to have a flag for which supports the 2MB part and who doesn't since everyone must support it. From a psychological point of view it will be much better for everyone to see that 2MB will happen, that in itself will discourage any false signaling.

Not everyone was a part of the agreement which means they may choose to not follow the HF. Due to the nature of hard forks there's simply no way to ensure there aren't going to be 2 chains.

> If there going to be anyone rejecting a HF then they will have to find some other way then signaling to make sure they are a majority.

You've mixed up hard forks with soft forks, hashpower majority only matters for soft forks in regards to being convergent, this is an incompatible HF like the ETH/ETC split was which means hashpower does not matter, each side just switches to their own chain.

**Comment by JaredR26** [comment]
> Not everyone was a part of the agreement which means they may choose to not follow the HF. Due to the nature of hard forks there's simply no way to ensure there aren't going to be 2 chains.

If they refuse to accept the agreement, they should be willing to fork onto a nonsignaling chain.  For those people who follow and use segwit yet still actively reject the compromise that brought us that, they should be forced to falsely signal.  Neither part of the charter is optional without the other.  That is how compromises in the real world work.  If people want to lie and fight back, no one can stop them, but we can make sure that they understand and that they must signal to follow the first part of the agreement.

> this is an incompatible HF like the ETH/ETC split was which means hashpower does not matter, each side just switches to their own chain.

Bitcoin is not ETH.  If the hashpower is 10%, it'll take half a year before the difficulty corrects; Nearly everyone will switch away from the un-usable chain.  It is looking like the hashpower refusing the fork will be less than 10%.

I just realized this isn't the signaling/orphan non-bit4 issue, mayhaps further responses on that in particular should happen on #40

**Comment by jameshilliard** [comment]
> For those people who follow and use segwit yet still actively reject the compromise that brought us that, they should be forced to falsely signal.

I don't see why.

> Neither part of the charter is optional without the other.

I think you don't understand how hard forks work.

> Bitcoin is not ETH. If the hashpower is 10%, it'll take half a year before the difficulty corrects; Nearly everyone will switch away from the un-usable chain. It is looking like the hashpower refusing the fork will be less than 10%.

Hashpower largely follows markets, the hashpower of the two chains will largely be determined by price at the time of the fork of coins on each chain.

**Comment by JaredR26** [comment]
> I think you don't understand how hard forks work.

Its called a compromise, and it is how the real world works.

> Hashpower largely follows markets, the hashpower of the two chains will largely be determined by price at the time of the fork of coins on each chain.

84% of the hashpower has committed to following this hardfork, so normal hardfork settlement processes are not relevant here.  This WG is operating under the assumption that the signatories will follow through.  It cannot simultaneously defensively code against a defection from within, deal with the inevitable chainsplit, satisfy the UASF timelines that it didn't even set, and still hit the timelines of the charter.  For all purposes in this github, it needs to be assumed that at least 84% of the hashrate will follow the hardfork for at least several weeks.

**Comment by jameshilliard** [comment]
> Its called a compromise, and it is how the real world works.

We live in a world constrained by engineering realities.

Based on [this](https://github.com/btc1/bitcoin/pull/6#issuecomment-304742280) comment:

> maximally compatible with segwit within the bounds of the charter

Mandatory bit4 signalling would not be acceptable.

**Comment by JaredR26** [comment]
> We live in a world constrained by engineering realities.

There's a thousand different ways that most things can be done.

> Based on [this](https://github.com/btc1/bitcoin/pull/6#issuecomment-304742280) comment:

Quoting that same comment:

> The high level charter is meeting the plainly stated "segwit AND 2m_base_blksz" outcome by coupling the two (rather than fully decoupled).

The issue you most frequently object to, that you usually describe as "impossible to do" (coupling the two) is explicitly a part of the charter.  Disliking that objective will not make it go away.

If bit1 signaling can be mandatory, so can bit4.  They mean the same thing within this working group after the lock in point, and the only thing being discussed is how to best fulfil the WG's objectives.

**Comment by jameshilliard** [comment]
> If bit1 signaling can be mandatory, so can bit4.

That does not comply with the WG goal of being "maximally compatible with segwit within the bounds of the charter".

**Comment by JaredR26** [comment]
> That does not comply with the WG goal of being "maximally compatible with segwit within the bounds of the charter".

Bit4 is not incompatible with Segwit any more than BIP148 is, which we already added compatibility for; Both lead to orphaning a small number of blocks, but do not otherwise affect wallets.

**Comment by jameshilliard** [comment]
> Bit4 is not incompatible with Segwit any more than BIP148 is, which we already added compatibility for

Mandatory bit4 signalling is unnecessary and counterproductive at it's designed to intentionally be incompatible, BIP91 seeks to be compatible with the existing segwit deployment as much as is technically possible. The code isn't strictly BIP148 compatible, the faster BIP91 just reduces the chance of a conflict.

> Both lead to orphaning a small number of blocks

Orphaning of blocks is something that should only be done out of necessity and should be avoided as much as possible.

Mandatory signalling also is likely to cause issues with the SPV mining a lot of miners use. When BIP91 mandatory signalling is active miners should disable SPV mining, having bit4 be mandatory afterwards would increase the time they would need to disable SPV mining.

**Comment by JaredR26** [comment]
> Mandatory bit4 signalling is unnecessary and counterproductive at it's designed to intentionally be incompatible, 

The charter is incompatible with pre-existing clients.  The purpose of this discussion is fulfilling the charter.

> Orphaning of blocks is something that should only be done out of necessity and should be avoided as much as possible.

I agree.  In this case, given the magnitude of the disaster if the minority fork doesn't die out in December, it is justifiable.

> Mandatory signalling also is likely to cause issues with the SPV mining a lot of miners use. 

Not any more than BIP148.  Orphaned blocks will be short-lived given the severity of the impact to miners, so it is just as tolerable of a trade-off for bit4 as it is for bit-1.

**Comment by jameshilliard** [comment]
> The charter is incompatible with pre-existing clients. The purpose of this discussion is fulfilling the charter.

There is nothing in the charter that says we should try and intentionally be incompatible.

> I agree. In this case, given the magnitude of the disaster if the minority fork doesn't die out in December, it is justifiable.

You're thinking about this only from your own perspective, there are clearly many users who would consider it a disaster if they were forced to follow a HF they opposed.

> Not any more than BIP148. Orphaned blocks will be short-lived given the severity of the impact to miners, so it is just as tolerable of a trade-off for bit4 as it is for bit-1.

Yes, it's an issue for BIP148 because there are no other options. It's a tolerable trade-off for BIP91 with bit1 only because it's a technical requirement there, since it's not a technical requirement for bit4 it would not be justified there.

**Comment by jli225** [comment]
@jameshilliard It's not mandatory. It's user-activated.
Anyway, users have the final say. Do you think your opinion is above users'? I don't think so.
Let's follow the user majority.

**Comment by jameshilliard** [comment]
Using a >1MB block wouldn't work since it's not SPV compatible, I've made a [PR](https://github.com/btc1/bitcoin/pull/46) that instead uses a hardfork bit to ensure that SPV wallets have the same wipeout protection capability.

**Comment by gavinandresen** [comment]
What SPV wallets are not compatible with >1mb blocks?

The (bitcoinj-based) wallets I tested a couple years ago don't care about the block size.

Or do you mean you want to force SPV users to upgrade to follow the >1mb chain? That would be a mistake, in my opinion.

--
Gavin Andresen

**Comment by luke-jr** [comment]
@gavinandresen I believe he is working from the premise that the goal here is to avoid a reorg risk from the smaller-block chain. Toward that end, using the hardfork bit allows pSPV nodes to detect which chain is which, and choose either way. Current nodes ignore it (IIRC) and will simply follow the one with the most work, but future versions can explicitly check for the hardfork bit beginning with Segwit+3months to ensure they follow the Segwit2x chain (or vice-versa).

**Comment by JaredR26** [comment]
Reorg risk relates to full nodes and the chain.  If James pull request is
actually about identification rather than compatibility, it seems to be
misnamed.

Are there any spv wallets not compatible with >1mb hard forks?

**Comment by MickSHunt** [comment]
seems this whole btc1 implementation is about making a bilateral split(altcoin) not a network upgrade.
with the change the service bit stuff and other things,, its less of a network upgrade and more of a network split with a 'hope' nodes choose Xchain later.

how about just stick with with current service bitcoin service bit. get rid of the 2 merkle(backward compatible) stuff.. 

and if this btc1 implementation activates then users have 3 months to upgrade or be left unsynced. 
thus only one network. so that its a mandatory upgrade and not an altcoin

rather then all this cludge and bilateral splits and fights over which chain is the best chain drama between now and 3-5 months time.

make it simple.. if activates, drama of choice ends and all thats left is just to upgrade within 3 months. end of debate

>  I believe he is working from the premise that the goal here is to avoid a reorg risk from the smaller-block chain.  Toward that end, using the hardfork bit allows pSPV nodes to detect which chain is which, and choose either way. Current nodes ignore it (IIRC) and will simply follow the one with the most work, but future versions can explicitly check for the hardfork bit beginning with Segwit+3months to ensure they follow the Segwit2x chain (or vice-versa).

seems luke is doing all he can to make things complicated. he even admits there would be 2 chains

> "detect which chain is which, and choose either way."
> "follow the Segwit2x chain (or vice-versa)."

**Comment by jameshilliard** [comment]
> What SPV wallets are not compatible with >1mb blocks?

They wouldn't be compatible with wipeout protection since they don't care about the >1mb block, you need something in the header so that they can detect the chain they are supposed to be on.

> Or do you mean you want to force SPV users to upgrade to follow the >1mb chain? That would be a mistake, in my opinion.

If they don't upgrade they would be vulnerable to having their chain wiped out.

> Reorg risk relates to full nodes and the chain.

It's the same risk for SPV wallets since they need the same wipeout protection as full nodes.

> If James pull request is actually about identification rather than compatibility, it seems to be misnamed.

It makes the SPV wallets compatible with wipeout protection same as full nodes, if SPV wallets can't detect the chain they are on they risk getting reorged.

**Comment by magmahindenburg** [comment]
I feel like there is a lot of bike shedding going on here. Too much fuzz about theoretical re-org risks. The fear of the legacy chain overtaking the new 2Mb is very small. The larger than 1Mb block rule is good for many reasons, but it's primary for miners and full nodes. There is no wipeout risk for SPV nodes since they follow the full nodes, so it's just a matter of connecting to the right node when it comes to choosing which chain to follow.

Edit: Most SPV nodes will get updated via Play Store and App Store anyway. Lets leave this to each wallet developer.

Since we have 90% of the miners signalling intent, there is no reason to worry about a split. If a minority chain will ever exist, it won't even reach one difficulty adjustment.

**Comment by jameshilliard** [comment]
> There is no wipeout risk for SPV nodes since they follow the full nodes, so it's just a matter of connecting to the right node when it comes to choosing which chain to follow.

The security model of SPV nodes is that they trust the most work valid headers chain, you are effectively saying SPV nodes would also need to trust the full nodes to connect to as well to determine the correct chain, that is a significant reduction in security.

> Most SPV nodes will get updated via Play Store and App Store anyway. Lets leave this to each wallet developer.

Wallet developers need a reliable way of determining which chain is valid, using a hardfork bit in the header gives them that capability.

> Since we have 90% of the miners signalling intent, there is no reason to worry about a split. If a minority chain will ever exist, it won't even reach one difficulty adjustment.

Miners largely follow the markets, you can't rely on hashpower signalling before the fork like you can with soft forks since hard forks like this one are non-convergent, since the HF is clearly highly controversial there's certainly a high chance of a split if the market favors or gives the original chain a non-insignificant value.

**Comment by jli225** [comment]
I prefer "Hard fork on Block X (specific value)", and I believe it will gain more support from the silent majority, because it was written by Satoshi.

**Comment by jgarzik** [comment]
There are notable attributes aside from wipeout protection,

* Producing the bigger-block conditions at a predictable time.  A bit in the block header doesn't do this.

* Maximizing compatibility with existing software in the field.   A bit in the block header reduces this.

(cc PR #46)

**Comment by dgenr8** [comment]
ACK at X+0.  Figuring out how to produce a block > 1MB can be left to miners.  They have plenty of incentive, and it's clear from the discussion above that different miners will want to do it different ways.

**Comment by jameshilliard** [comment]
> Producing the bigger-block conditions at a predictable time. A bit in the block header doesn't do this.

Using the hardfork bit ensures that the new chain is not compatible with the existing chain.

> Maximizing compatibility with existing software in the field. A bit in the block header reduces this.

It depends on if one thinks it matters that SPV wallets have wipeout protection and the ability to choose a particular chain. The HF bit technique was designed so that SPV wallets function in the same way as full nodes in regards to being able to validate the fork. This isn't really even an issue for many wallets only those that are SPV and not centralized validator wallets and it should be trivial for wallet authors to update them since most are distributed via app stores.

**Comment by jgarzik** [comment]
Merged as PR #50
