### ISSUE TITLE
Allow only one transaction over 100kb.

### ISSUE THREAD

**Issue by chjj** [btc1/bitcoin#32]
Two 1mb transactions can still be trouble as far as DoSing goes. Since segwit2x is a controversial change, I expect the possibility of DoS attempts on the network.

I suggest we allow only _one_ transaction over a base size of 100kb. This one exception can be up to 1mb base size. For every other transaction in the block, the consensus limit is 100kb (this is already the policy limit anyway).

Example:

```
Block 1: tx1 (1mb), tx2 (100kb) -> valid
Block 2: tx1 (1mb), tx2 (1mb) -> invalid
Block 3: tx1 (1mb), tx2 (101kb) -> invalid
Block 4: tx1 (200kb), tx2 (100kb) -> valid
Block 5: tx1 (200kb), tx2 (101kb) -> invalid
etc...
```

Ideally, I think it would be good to require _every_ transaction to be 100kb or below, but this could invalidate existing pre-signed 100kb-1mb transactions, so there's some philosophical issues with that.

I think this is a much safer and more conservative strategy for tackling the sighashing issue. There's really no reason for a block to have _two_ 1mb transactions. I can't think of a justification for it.

We have to consider that there are blocks on the chain right now which take upwards of 30 seconds to verify on an i5/i7. Two 1mb transactions could easily result in more than 1 minute of verification time. Maybe that doesn't sound so bad, but when you take into account the fact that it is an entire _one tenth_ of the block time, things start looking a little screwy.

I hope this isn't a controversial suggestion, since it doesn't actually limit throughput at all. If someone wants more inputs/outputs, they can simply split their transaction into multiple transactions.

**Comment by hoffmabc** [comment]
If the max tx size currently is 1MB are we currently seeing DoS problems with 1MB transactions? 
I think this sounds like a reasonable compromise in terms of allowing those pre-signed txs at least an opportunity to be mined. Do we have any idea the magnitude of how many of txs there are?

**Comment by jgarzik** [comment]
Comments:
1) There are ways to discourage besides making it a hard consensus requirement.  Example:  You can make transactions over X bytes non-standard, and not relayed by the client normally.

2) With a hard or soft requirement, there is still wallet compatibility to consider.  Some wallets may generate a large tx in a valid situation such as sendmany.

**Comment by gavinandresen** [comment]
Non-segwit transactions larger than 100K are already non-standard (segwit transactions can be up to 400K) and won't be relayed or mined.

I think it is a bad idea to add more consensus-level rules; keep them as simple as possible.

**Comment by chjj** [comment]
@jgarzik & @gavinandresen,

This is more a case of a miner trying to DoS the network. Even a small miner with 0.7% hashrate can mine 1 block a day containing two 1mb transactions. 

Obviously major mining pools are unlikely to ever intentionally do this, since they have enough skin in the game, but there's always the chance of a worst case scenario: say, for instance, the connection between a major pool's node and their stratum server getting MITM'd by someone trying to break bitcoin. The system should be resilient against even the unlikely scenarios.

I don't think wallet compat is an issue, because wallets should not be creating >100kb transactions in the first place. If they do, they're already going to run into issues due to violation of policy rules.

**Comment by gavinandresen** [comment]
Miners do not intentionally create expensive-to-validate blocks; it is against their financial interest.

The dangers of adding Yet Another Arbitrary Consensus Rule are:

1) More code means more possibility of bugs.

2) In ten years there is another rancorous debate about the transaction size limit, because post-quantum crypto or sidechains (or something) needs >100KB transactions.

**Comment by chjj** [comment]
> Miners do not intentionally create expensive-to-validate blocks; it is against their financial interest.

Yes. I agree, but the worst case situation I described above still applies: a mining pool operator may not always be in control of their pool.

> In ten years there is another rancorous debate about the transaction size limit, because post-quantum crypto or sidechains (or something) needs >100KB transactions.

Doubtful. Arbitrary groups of inputs and outputs can always be split into multiple txs if necesary, and witness vectors don't count against the base size, so it's hard to think of a case where that's necessary. No transaction technically _needs_ to be that large in base size unless they have some very strange need to fit >100kb of data in a single output script or something (which would make the script unredeemable, but maybe it's being used as a data carrier???). That's a really weird case. If it needs that, I would say whatever protocol doing that is mis-designed.

In any case, they can still get mined, just 1 per block.

**Comment by benkloester** [comment]
Isn't the DOS risk post-HF only twice as bad? I know validation is o(n^2) in transaction size, but the consensus limit is still 1MB in both cases, so 2x 1MB transactions is only twice as bad as what is currently possible right?

Changing consensus rules to avoid a 2x increase in DOS severity seems pretty extreme. The limit is already 1MB, what are the factors for why we don't we already see these sorts of attacks now, and why wouldn't those factors apply post HF?

**Comment by theslagter** [comment]
bitcoin has had good standing among the worlds hackers etc. which is part of the reason its not attacked and vulnerabilities are disclosed instead. However, the NYA chain will not be in good standing because it isnt about crypto anarchy. You will find people picking your chain and software apart and use any exploits available rather than disclose them. So be careful.

**Comment by chjj** [comment]
> Isn't the DOS risk post-HF only twice as bad?

For sighashing, yes, but there are more unknowns. For example, there's also double the UTXOs that need to be accessed in a worst case 2mb block. To increase block processing time, a clever attacker would not only create two 1mb transactions, they would also redeem UTXOs that were created several hundred blocks ago, to ensure no cache hits. They would also use no shared txids (since bitcoind stores utxos by txid) and redeem only outputs whose parent transaction contains _tons_ of outputs. This would require a db access for every input and require reads of massive amounts of data. 

We may never have even seen a _real_ worst case block on the 1mb chain yet. There's no telling what a worst case block could do to the 2mb chain. I think we should try to mitigate these risks as much as possible.

I've opened a PR for this issue: #41.

**Comment by christophebiocca** [comment]
> For example, there's also double the UTXOs that need to be accessed in a worst case 2mb block. To increase block processing time, a clever attacker would not only create two 1mb transactions, they would also redeem UTXOs that were created several hundred blocks ago, to ensure no cache hits. They would also use no shared txids (since bitcoind stores utxos by txid) and redeem only outputs whose parent transaction contains tons of outputs. This would require a db access for every input and require reads of massive amounts of data.

While what you describe is plausible (I'm not familiar enough with the Satoshi client's perf characteristics to put real numbers on it), there's no superlinear cost to UTXO lookup, so the harm, on that front, of 2 big transactions is the same as that of 2000 smaller ones with the same inputs.

> We may never have even seen a real worst case block on the 1mb chain yet. There's no telling what a worst case block could do to the 2mb chain.

This seems like it should be testable on testnet5.

**Comment by jgarzik** [comment]
Re-Reviewing this whole thread, thanks for all the thoughtful comments.

I do understand the attack vector.  However, this is ultimately introducing complexity for an unlikely case when a miner is acting directly contra to short term and long term interests.  These transactions won't get relayed, so you need a significant investment just to have a possibility of success.

The relay policy + a simple, consistent consensus behavior should have the least unintended consequences.

Still leaning no but want to hear any further feedback.

**Comment by dgenr8** [comment]
A use for large transactions in general is the transaction as the atomic "all-or-nothing" unit.  Either everybody gets paid at the same time, or nobody does.

**Comment by moeadham** [comment]
@chjj Very much agreed on the attack vector, and great work trying to point out a simple solution to it.

That being said, I agree that adding more consensus code is not worth it., especially ones that have hard-coded values (ex 100kb). Tx's over 100kb are already non-standard for relay; miners can already create 1MB transactions all they like right now, and do it very, very rarely. 

I would lean no on this one to keep conflict to a minimum.

**Comment by jgarzik** [comment]
concept ACK

**Comment by zander** [comment]
About the attack vector;  https://zander.github.io/posts/Quadratic%20Hashing/

**Comment by christophebiocca** [comment]
> About the attack vector; https://zander.github.io/posts/Quadratic%20Hashing/

Do you have more info on the caching fix for quadratic hashing? We might as well do that instead since it'll protect us against even one really bad 1MB transaction.

Sergio seems to say caching doesn't help (without doing a hard fork to make it work).

**Comment by zander** [comment]
@christophebiocca https://github.com/btc1/bitcoin/blob/segwit2x/src/script/sigcache.h

**Comment by nathan-at-least** [comment]
Wandering in from Zcash with some thoughts/lessons and potential collaboration:

**Summary:**

I urge you to develop (reproducible, automated) benchmarks that attempt to approximate the performance cost; we have some that may be useful already, and we should collaborate on adding more. Making these design decisions without doing so seems excessively risky to me.

**Zcash Design:**

Zcash introduced a _consensus rule_ limit of 100Kb per transaction. This was a somewhat rushed decision to avoid the `SIGHASH_ALL` quadratic verification issue.

@gavinandresen and other's concern about introducing a consensus rule are quite valid. I don't think Zcash has worked through all the knock-on effects of this particular rule modification (for example, our own wallet and probably many third party wallets probably handle >= 100KB poorly).

However, note that there _is_ an advantage: with a consensus rule there is _no ambiguity_ about why a transaction fails. Any wallet or node can immediately _locally_ determine the transaction is invalid. With node-customizeable relay rules or other configurable policy, it becomes a challenge to communicate to users why transactions fail. ("Was it relayed? Who rejected it? Why? Do miners have it in their mempool but choose not to mine it? Why?")

Configurable policy may be the better choice for Bitcoin. In any case, the disadvantage of configurable policy needs to be overcome by better user feedback about, and control of, the fate of transactions, which is yet another of the many design space areas that Zcash and Bitcoin can benefit from mutual collaboration.

**Zcash Performance and Benchmarks:**

We're forked from Bitcoin Core v0.11.2, and it turns out we still have poor performance for sub-100Kb transaction verifications with 2MB blocks. For example, `getblocktemplate` takes too long for miners: https://github.com/zcash/zcash/issues/2333

Prior to our launch we created some benchmarks for large-transaction signature verification. They were introduced in: https://github.com/zcash/zcash/pull/1046 Those tx-specific benchmarks aren't capturing the actual cost of users such as the `getblocktemplate` issue above, so we need to add more benchmarks, such as https://github.com/zcash/zcash/issues/1077

**Shared Benchmark and Test Infrastructure:**

These are benchmarks that should be shared among Zcash, Bitcoin Core, and BTC1. Using similar benchmark code on systems with segwit and those without and those with different transaction size limits will be beneficial for all of us in understanding the design space tradeoffs, so it would be awesome if btc1 ported those benchmarks.

In fact, if btc1 had those benchmarks in trunk, Zcash would like to hook btc1 benchmarking into our own reference machine to track Zcash's performance in comparison to more performance-improved btc1. It could easily be the case that there are existing Bitcoin benchmarks that our small overloaded team isn't yet aware of, in which case I'd love pointers.

In general we'd like to share resources and collaborate on test infrastructure, benchmarks, continuous integration, etc… for all of the substantial portions of our design that overlap. Doing so will bring clearer data about available trade-offs to both systems. Currently we lack the resources to do much here, but that should change as we grow our team.

**Politics:**

I realize there're tensions Bitcoin Core (https://github.com/bitcoin/bitcoin/) versus btc1, but I have little opinion about them and don't see them affecting anything I've said here. Practically, everything I've said about collaboration applies to both projects, and the primary reason I'm posting here is because your design discussion has wandered directly into an area Zcash has explored.

**Comment by maddenw** [comment]
Make transactions over 100k non-standard now and readjust later. Duh. Is this here for politics again?

**Comment by daira** [comment]
Also from Zcash: I don't think there has been any problem due to our decision to limit txns to 100K as a consensus rule, and I find it much easier to reason about quadratic-scaling DoS attacks as a result. In fact I wish we'd limited it to 40K.

**Comment by jgarzik** [comment]
Given that >100k transactions are already non-standard, this one never really garnered much interest.

Closing now simply to limit scope.

Worth revisiting in the next fork/update, especially given Zcash feedback a la @daira
