### ISSUE TITLE
Suggestion to add softfork rule: no hardfork means no SegWit

### ISSUE THREAD

**Issue by ATBP** [btc1/bitcoin#45]
When fSegwitSeasoned and no block with over 1mb base size yet, then new block containing SegWit data is invalid.

Reasons: outside the NYA group, there is sometimes sentiment the SegWit and hardfork part are independent. This misunderstanding might lead to inaction from their part and after activation of SegWit there is real risk of Bitcoin split when fSegwitSeasoned. This rule should clear up any misunderstanding and put incentive to find widespread scalling consensus while avoiding Bitcoin split, which I believe is in the spirit of NYA.

This softfork rule also prevent big reorg should there be two chains after fSegwitSeasoned.

**Comment by Buck-Rogers** [comment]
@ATBP I agree with what you are saying and your sentiment, it is something that concerns me also. I am uncertain that is a solution however as any miner can get out of bed in the morning and just start running a different client. It would have been better if the segwit activation and HF were done at the same time, this 3 month window will not be pleasant.

Maybe you could explain your solution with code?

**Comment by jameshilliard** [comment]
NACK, this is dangerous and could result in unspendable coins.

**Comment by Buck-Rogers** [comment]
@jameshilliard 

> this is dangerous and could result in unspendable coins.

The same could be said of segwit itself.

**Comment by JaredR26** [comment]
This would go against the spirit of the agreement, as it would not
"activate segwit" until 3 months had passed.

Perhaps as a soft fork rule instead, this client could treat as invalid any
segwit blocks that are over 33% segwit transactions until the hard fork
activation?  That would give a small bump in capacity for the 3 months and
satisfy the charter, but still provide motivations for cooperation with the
hard fork...

**Comment by JaredR26** [comment]
Actually thinking about it, there's no way this rule could be added and
tested in time.  NACK based only on that.  A rule could be added after this
pass of testing that orphaned blocks conditionally but would accept them
after they had been mined upon, thus preventing a launch problem, but
that's still a bit much to test and launch when the main goal is just to
launch the hardfork and deal with the inevitable chainsplit caused by the
opposition.

**Comment by ATBP** [comment]
This would add the possibility for the NYA group to continue mining on the 1MB chain if it become clear SegWit2x code is not widely adopted even after 3 months after SegWit activation, thus preventing Bitcoin split. In this case preventing adding new SegWit transactions to the blockchain after those 3 months and until SegWit2x code is widely adopted is logical step because it provides incentives for SegWit2x code adoption.

**Comment by jameshilliard** [comment]
> In this case preventing adding new SegWit transactions to the blockchain after those 3 months and until SegWit2x code is widely adopted is logical step because it provides incentives for SegWit2x code adoption.

That's not really possible, you would only know the transaction uses segwit(at least for P2SH wrapped segwit transactions) when you try and spend it.

**Comment by ATBP** [comment]
@jameshilliard I meant SegWit data must be zero in size, ie there can not be reference to the SegWit hash in coinbase for the block to be valid.

**Comment by opetruzel** [comment]
NACK.

**Comment by jameshilliard** [comment]
@ATBP SegWit UTXO's would be unspendable then which would not be good. The hash in the coinbase is needed for spending SegWit UTXO's not creating them so this could lead to lost funds as UTXO creation would not be restricted.

**Comment by ATBP** [comment]
@jameshilliard SegWit UTXO's would be normally spendable again the moment first block with over 1mb base size is added though. So I dont get your argument it could lead to unspendable coins.

**Comment by jameshilliard** [comment]
@ATBP They would be unspendable before that when wallets would assume segwit is active due to bit1 activation, so coins could get locked up in the time after activation and before the base size increase.

**Comment by Buck-Rogers** [comment]
NACK, I like what you are trying to do. But I do not think it will work.

**Comment by christophebiocca** [comment]
This is incompatible with #29, since once Block X is reached, as far as the code is concerned, only a branch with a >1MB block is valid.

The code you're suggesting to be added would then do nothing at all. And since "to continue mining on the 1MB chain" would require code changes anyways, any special extra soft-forks could be introduced at that time.

Although if we're expecting the miners to play hardball and force stragglers into accepting the new rules, why not do a generalized soft-fork that completely disables transactions in the "legacy" blocks, and puts all transactions onto an extension block (the hash of which is in the coinbase)? That's actually pretty easy to do, avoids a chain split, and is much more effective at forcing people to upgrade (they have to choose between hard-forking away from SHA256, never receiving or sending bitcoins ever again, or upgrading to the new protocol).

If you're going to push for a coercive soft-fork to get >1MB blocks, make it as effective as possible, and make it *actually* have >1MB blocks.

**Comment by jgarzik** [comment]
Basically echoing @christophebiocca , the code is written to assume the hard fork happens on block X[+n], making this request largely a no-op from that standpoint.
