### ISSUE TITLE
Signalling bit1 is wrong message to BIP148 supporters

### ISSUE THREAD

**Issue by Zaromet** [btc1/bitcoin#52]
I agree there is no technical reason not to signal bit1 if you plan to activate SegWit anyway. But there are hard fork political reasons. We need to look at political reasons since 2MB fork is political too.

1. Extreme users that are now signalling BIP148 will not go way. They will say they won and use "BIP148" argument to stop HF.
2. Since they have "won" many less extreme users will follow.
3. Extreme smallblocker that says "Even 1 MB blocks are already clearly dangerous to Bitcoin"(Even when pushing BIP148 that takes blocks by his mathematics to 2-4MB) will be seen as a hero and will be able to block HF more effectively...
4. It only propositions chain split and make sure we have only 1MB vs SegWit2x and not 1MB vs BIP148 vs SegWit2x. It is highly likely that 99% of support for BIP148 will got to 1MB chain. So that also reduces chances of successful HF...
5. SegWit2x will give users SegWit so pushing BIP148 it not about SegWit but giving more power to extreme smallblocker.
6. It looks like they will have less then 16PH of mining power and they will have to HF with POW change and difficulty reduction to make a chain usable and be able to activate SegWit...
7. Signalling bit1 was not part of a agreement.

There are probably more reasons not to do it but since a chain split is coming anyway I really don't see a reason to accommodate and give more power to users that will do anything to stop later HF.

**Comment by christophebiocca** [comment]
Signalling bit 1 isn't just for the benefit of BIP148 users. It's the normal signalling bit for SegWit activation, including all releases of bitcoin-core (none of which use UASF).

If you want to fork UASF off the network, the simplest solution is to keep bit4 signalling under 80% until after the UASF activation is reached. No code changes required. Just convince one or 2 miners to not signal fully until after that time.

**Comment by Zaromet** [comment]
Agree but I disagree that technical reason would be used to explain what happened. Just go to Reddit to understand that.

Also as far as I understand nonbit 1 blocks will be also orphaned once SegWit2x activate(correct me if I'm wrong)... I get signalling bit1 but do not get orphaning if it is not for and only for BIP148 users. And why were times decreased if it is not for that. I would like to see an option not to signal bit1 if I would like to wait but signal bit4 ASAP.

**Comment by christophebiocca** [comment]
You need orphaning to get nodes that are waiting for 95% signalling to actually activate (because 95% was the original activation threshold).

The timeline goes like this:

1. 80% bit4 signalling.
2. Orphaning of non-bit1-signalling nodes.
3. 95% bit1 signalling.
4. SegWit lock-in period.
5. Segwit activates. At this point bit1 is no longer needed.

You could hack this up by having a deterministic orphaning rule that invalidates most, but not all, blocks not signalling bit1 (a non-bit-1-signalling block is invalid *unless* the 3 low bits of the header hash are all 0), just to force BIP148 off the network.

But what's the point? They have essentially no hashpower (so they won't diverge, just be stuck at block XYZ) and they can just change their nodes back to run regular core code once segwit activates on the main chain. It's not like they're permanently committed to their fork and nothing can make them switch back (especially if they have to choose between a main branch that already has Segwit deployed and one that would activate it faster in blockheight terms, but slower in real terms). You're assuming that forking BIP148 off the network will actually do something meaningful, but that's nor true.

Again, what you want can be achieve much more easily by convicing 5% of hashpower to delay segwit2x until August 2nd than by introducing epicycles in the codebase.

**Comment by Zaromet** [comment]
As far as I get the code I need to stop SegWit2x from activating since it will start orphaning nonebit1 blocks so I don't need 5% but about 25%(just to be safe since a variance factor with that small number of blocks is bigger then with 1000). Or were you talking about SegWit2x miners? And my goal is not to delay SegWit2x but just to let BIP148 to have there own fork...

Also I disagree there is no point. There is a big reason to do that and it is a social/political one. They can't declare victory. And with Reddit and Bitcointalk the way it is this will give them a lot more power to stop HF latter since they are already saying SegWit2x is happening because of BIP148. I'm fine with them to rejoin with normal core code but there will be less of them since less extreme users will not join them and less extreme among them will see that bitcoin is POW not Prof of IP or whatever... And there is a big chance one of the coredevs will make a permanent HF with POW* and difficulty change that will hurt core case since coredev did a HF without overwhelming community support. 

*At this point I think I need to disclose that I have also a GPU miners not only a SHA256 miners. I don't see them on that fork but money is money and there is a price point that might be hi enough to do it...

**Comment by RHavar** [comment]
I think you misunderstand the intentions behind SegWit2x: It's about a good faith effort to find common ground and move bitcoin forward. This goal is not advanced by trying to spit in peoples faces.

**Comment by Zaromet** [comment]
I understand that part. Problem is that if reasons are social/political not technical you can't allays assume that. Even more when you see evidence of bad faith. BIP148 at this point is not good faith but a spit in people faces to make them weaker at a later date... Assuming good faith with a close group that agree to this is OK but this will also be used outside with a open group that didn't agree to that. I know that makes things paranoid but they are paranoid with good reasons. If only technical arguments were used there is no reason to oppose SegWit since Core will follow it with 2MB fork right? We seen what happens in HK and HF code we got(300kb to start with). SegWit is blocked with a reason that is not technical. If we assume good faith BIP148 is out there without a reason at this point but it is still heavily promoted by a coredev and SegWit2x is heavily attacked by same coredev. You can see it is grab for additional power to stop 2x part of SegWit2x and bit1 before Avg 1st will give him that. And now that he see there is no risk of doing that he is already double down(POW and difficulty HF)...

**Comment by jli225** [comment]
Concept Ack.
We have the obligation to inform those people who have been brainwashed or confused by censorship and propaganda about how the Bitcoin community majority will move forward, in case some people have the illusion that they are the manority.

A lesson is need for people who suffered lies in that echo chamber.

@RHavar  I appreciate your good intent. However, although most of us have already found the common ground, there are some people outside who attack this project like crazy. Recently, we have known how unashamed they were and how blatant their lies were. We shall keep in mind how those poisonous guys hijacked the Core, so that we can avoid similar tragedy.

This is how the society works. If the bad guys join in, if ill-intentional actions are not punished in time, good guys will leave or never come in. We have already lost Mike Hearn and many great heros.  It's enough. That's why many Bitcoiners see the SegWit2X as the last hope of the Bitcoin community.

**Comment by aceat64** [comment]
> A lesson is need for people who suffered lies in that echo chamber.

Software should not be used as a punishment. That completely defeats the main goal of this project as @RHavar pointed out.

**Comment by JaredR26** [comment]
For better or for worse, this ship has sailed.  I proposed many similar arguments about bit1 vs bit4, and still feel that bit4-only would be safer.

But that is neither here nor there; The decision was made not to do that, and that decision was made for justifiable reasons.  The miners may now make a choice about the smoothness of the activation regarding your BIP148 points, and that's their choice.  While your points on BIP148 are not necessarily wrong, it may be better to extend an olive branch than a sword; At some point the community needs to begin coming back together, or else it will (and needs to) split for good.

**Comment by Zaromet** [comment]
I would love not run a btc1 code but a core version of what is in HK agreement(the way a person reads it not some legal interpretation) so I'm all for olive branch but at some point I see too much of same old... Well lets hope I'm totally wrong if all is set in stone.

Also I can't see how this can be seen as a punishment. It is compatible with "reference client" at the time that I'm talking about... By that logic 2MB HF is more of a punishment since this one is not compatible with "reference client". And by that logic if I fork of using EC I'm punished? No it is my decision and BIP148 is also a user decision. So what I suggested is just a reality check.

**Comment by jli225** [comment]
@Zaromet 100% agree. "reality check" is necessary.
@JaredR26 I appreciate your good intentions and I wish my comment below not be destructive.

However, the Bitcoin community---Gavin, Mike Hearn, Coinbase, Bitpay, Bitmain, Blockchain info, BU, Roger--- all of us have shown too much good-intent to current Core. Unfortunately, they did not see it as an olive branch, instead, they saw our kindness as weakness. So they divided and conquered every time. It's the indifference and inaction of the Bitcoin community that caused the left of Gavin, the quit of Mike Hearn, the frustration ~~and~~ of Coinbase, the "vote with feet" of so many users.  

I am always curious why the censorship in that reddit sub is accepted without anger by many people who want a censorship-resistant money. Maybe one important reason is that it seems that the only way to avoid community split is to make the Bitcoin community follow/obey the Core on everything, now that current Core won't change in any case and they won each time by "divide and conquer" strategy.

So, I deem that "reality check" is necessary, especially for those people who have been brainwashed.

**Comment by aceat64** [comment]
Please stick to technical matters and stop flooding this project with
pointless and divisive political discussion. This isn't reddit, this is a
place for technical discussion and cooperation.

**Comment by nyhele** [comment]
Forget about this project. That the maintaining leave @jli225 comments up speaks alot to how the people behind it thinks.

**Comment by jgarzik** [comment]
(delete a zero content troll comment)

Closing - this isn't the place for high level political discussion - Basically agree with @christophebiocca @RHavar @aceat64
