### ISSUE TITLE
[Serious] How would you define Bitcoin?

### ISSUE THREAD

**Issue by nyhele** [btc1/bitcoin#66]
How does BTC1 supporters see Bitcoin? What do they consider it is? A short definition would be helpful.

Im not sure how i woul define  bitcoin myself, but a definition is important i think since it can guide us for what to code and how to approach it etc.

**Comment by christophebiocca** [comment]
Issue trackers are a poor place to discuss philosophy but:

> Bitcoin: A Peer-to-Peer Electronic Cash System

Is still a really good one sentence summary, 8 years later, in my opinion.

**Comment by jcansdale** [comment]
I think a practical definition of Bitcoin will be something like this:

> The block chain with the highest market cap that originates from the Bitcoin genesis block.

**Comment by JaredR26** [comment]
> I think a practical definition of Bitcoin will be something like this:

> > The block chain with the highest market cap that originates from the Bitcoin genesis block.

This issue isn't related to technical issues and will probably be closed(and should be).  But just food for thought for both sides, I don't think that definition is quite complete.  The definition of "Bitcoin" under a fork scenario should be crystal clear - it should be the chain (originating from Genesis) with both the highest market cap and the most proof-of-work backing it.

If there isn't a blockchain that has both of those simultaneously then we are in an unstable equilibrium that hasn't had time to resolve itself, and there is neither a "false" bitcoin chain nor a "true" bitcoin chain.  Either the market cap will switch due to a lack of security/blocks, or the mining distribution will rebalance around the appropriate saturation points for each.  Proof of work guarantees that the two cannot diverge over a sufficiently long period of time.

**Comment by nyhele** [comment]
@christophebiocca this definition does not seem to fit the goal of this peoject which is to turn bitcoin into a payment rail for coinbase, blockchain.info etc. what i dont get is why they dont design their own settlement/transaction system. It has the potential to be much better than on-chain transactions. People who use coinbase and blockchain.info are noobs anyway and  not into bitcoin for its on-chain transactions. People who are into this use tools and software that is more secure and private.

**Comment by jcansdale** [comment]
> The definition of "Bitcoin" under a fork scenario should be crystal clear - it should be the chain (originating from Genesis) with both the highest market cap and the most proof-of-work backing it.

This is the problem. I think it will become clean in hindsight, but not necessarily as the fork happens. I wanted a definition that works in the face of a PoW change (who knows what will happen with quantum computing 😉). If PoW has a tendency to follow the market (Bitcoin's security is based on this assumption), why not incorporate the market into its definition?

Maybe this falls apart under certain scenarios, but it wasn't obvious to me when. An interesting question anyway.
