### ISSUE TITLE
Rules for extra Lightning security

### ISSUE THREAD

**Issue by jgarzik** [btc1/bitcoin#7]
@chjj requested consideration of "Rules for extra Lightning security", as described at https://github.com/tothemoon-org/extension-blocks/blob/master/spec.md#rules-for-extra-lightning-security

Is there a change that can be made to enhance Lightning security?  Now is the time, before things are locked in stone.

**Status**: Unscoped
**Process Note**: This is outside the scope of the SegWit2x charter; post-Milestone1 material.

**Comment by jnewbery** [comment]
NACK. This is an ugly hack. The bitcoin consensus layer shouldn't be abused for the sake of any individual second-layer application. This makes consensus rules more complex for the benefit of a subset of users. It also adds a lot of complexity to the transaction selection problem for miners, which is already a multidimensional nonlinear knapsack problem. There are very good reasons to make transaction selection as simple as possible, since it provides some level of predictability for users of which transactions will be selected for the next block.

Specifically, making transaction validity for 'pre-allocated space' dependent on the last 2016 blocks means that miner transaction selection must track and update state for transactions based on its parent transactions (eg transaction x is valid for pre-allocated space up to block height y, but is then only valid for normal space). That's a very complex problem for the transaction selection algorithm when combined with re-orgs, CPFP tx packages, etc.

We want transaction selection to be fast (since any delay in creating new blocks increases the network orphan rate) and simple (for predictability).

Furthermore, I'm not convinced that 'pre-allocated' space will only be used for lightning. I imagine people will start using it for general-purpose priority transactions, where they're willing to pay extra for some higher probability that the transaction will get included. Transaction fee is the mechanism we currently have for that. We shouldn't add a new overly complex and specific alternative mechanism.

**Comment by hoffmabc** [comment]
This is an interesting response to this question @jnewbery. Do you see any case where it would be reasonable to augment simple fee based priority of transaction acceptance with a different or additional modification? Or would you consider fee based inclusion as the canonical solution going forward?

**Comment by jnewbery** [comment]
I don't want to rule it out entirely, but I think there would need to be a **very** compelling argument to make transaction selection and consensus rules more complex.

The old concept of transaction 'priority' based on coin age was removed from bitcoin core recently. That was a big step forward because it wasn't being used consistently by miners (why would it be?), so removing it gives more predictability for users that higher fees => higher chance that tx will be included in the next block. Priority was simply a policy rule for miners though. This is worse since it changes *consensus* rules. Making two classes of transaction (those that can be included in pre-allocated space and those that can't) would be two steps backwards in my opinion.

**Comment by chjj** [comment]
Late to this. Some history here: Joseph added these rules to our extension block proposal due to the lightning "flood attack" -- a malicious actor closing out a high number of channels prematurely en masse, flooding the chain with commitment transactions and requiring the other party to broadcast their corresponding penalties. The attack seems easier to pull off than people might think.

> The bitcoin consensus layer shouldn't be abused for the sake of any individual second-layer application.
> ...
> Furthermore, I'm not convinced that 'pre-allocated' space will only be used for lightning.

It's actually not meant to be used solely with lightning. Lightning is just a good example. It can be used for __any__ time critical smart contract. Any layer 2 contracts with a time component are affected by this attack, which is mitigated through this special versionbit behavior.

>  I imagine people will start using it for general-purpose priority transactions, where they're willing to pay extra for some higher probability that the transaction will get included.
> The old concept of transaction 'priority' based on coin age was removed from bitcoin core recently. That was a big step forward...

This is nothing like the priority system. It simply means that transactions with a particular version bit set count as being larger than they actually are. As a result, they must pay extra fees for the space they're taking up. The corresponding penalty transaction should also pay a fee, albeit lesser. The bottom line is, it will be in the miner's best interest to mine these transactions. This wasn't the case with the priority system.

I really don't see how it could be abused. If you want to pay higher fees to get a _second_ transaction confirmed faster, you can do that, but wouldn't it have been easier to send just one transaction with a high fee? This version bit thing is a very special use case. I don't think it's really useful for anything but time-critical predicates.

> Specifically, making transaction validity for 'pre-allocated space' dependent on the last 2016 blocks means that miner transaction selection must track and update state for transactions based on its parent transactions (eg transaction x is valid for pre-allocated space up to block height y, but is then only valid for normal space). That's a very complex problem for the transaction selection algorithm when combined with re-orgs, CPFP tx packages, etc.

It only needs to track the UTXO height & version, which bitcoind, bcoin, and btcd already do (and also bitcoinj?). I don't see it as terribly complex, but I'll see what it looks like after I try a preliminary implementation in bcoin. Maybe it requires some separate mempool index or something.

So main arguments for it:

- Lightning will now be secure against this attack.
- It applies to _any_ other time-critical smart contract, not just lightning.
- It doesn't seem to be abusable in any way.
- I think the implementation is much simpler than it sounds.

In any case, I suppose this change can be soft-forked in later, but it would be nice to have it right out the gate if we're going to have lightning right out of the gate. It's something @josephpoon has been trying to warn people about for a while, but it's fallen on deaf ears.

**Comment by jli225** [comment]
Hi jgarzik, thank you so much for making Bitcoin great again.

**Comment by maddenw** [comment]
NACK. That's a hack. Level 2 solutions are a dilution of the properties that make peer to peer unique data exchange interesting. The routing isn't decentralized; hubs benefit from scale, meaning the economics will create bank hubs. Plus, mass channel expiration attacks... Seems like corporate venture capital influence is the only reason we are even having this discussion. Skipping records here. Stop.

**Comment by jgarzik** [comment]
Closing - it's an uphill battle to solve Layer-2 issues at Layer-1.
