### ISSUE TITLE
What is the biggest reason to use BTC1? 

### ISSUE THREAD

**Issue by snavsenv** [btc1/bitcoin#95]
Hi. Does anyone have an elevator pitch for BTC1? Whats the biggest reason to run it? Thanks :)

**Comment by schildbach** [comment]
It implements the current consensus.

**Comment by snavsenv** [comment]
Which is?

Btw. i think you spelt Consensus wrong.

**Comment by cloudscape-germany** [comment]
Consensus is to 

1) **avoid possible chain wars** like we've seen with ETH and ETC chains (Price dropped by 75%). UASF (BIP148), which really is a hardfork too (not accepting votes for a competing chain), also could lead to such 51% chain wars in BTC. In order to avoid such, in New York over 80% of all BTC business and miners arrived at an agreement to implement BTC1 and after that the original Segwit proposal.

2) **taking out the signature of the block** does only give you that much more block size and consequently transaction speed. In order to be able to compete with faster Blockchain technologies like Steem, Bitshares or to-be-done EOS, BTC1 afaik quadruples the Blocksize by doubling the BlockSize to 2MB and separating the transaction signature.

3) **doubling block size** - see 2.)

4) **staying democratic** - BTC1 is democratic since it's a hard fork, meaning BIP91 has the democratic votes of the pools and nodes going for it in addition to the NYA.

In my opinion, while it _may_ seem too much of a fuzz for a minor speed and size increase, discourse and opposition is the very foundation of democracy. That the discussion is staged transparently is to be considered a strength not a weakness.

Talking of transparency.. there are critics of BTC1 and I think a few major points are mentioned in this blog post: https://xbtdev.com/segwit2x-review/.

**Comment by KY-BChain** [comment]
Maybe we need to look at BTC1 etc from the other way. What happen if we do nothing ?
